### ISSUE TITLE
Graz fixtures - super user accounts were wrong

### ISSUE THREAD

**Issue by aaronkaplan** [FunkFeuer/Graz#42] opened 2015-06-07 10:43 UTC
The fixtures for the superusers were wrong for Graz.

**Comment by tanzer** [comment] 2015-06-18 17:47
Fixed in https://github.com/FunkFeuer/Graz/commit/ce2fcf2fb65c4d277b7bb61ecfb00b5344bba378.

The fixtures are defined in fixtures.py.

Ralf: please fix encoding issue in converter (Jürgen Schweizer) and pass on to the Grazers.

**Comment by schlatterbeck** [comment] 2015-06-20 16:32
On Thu, Jun 18, 2015 at 10:47:42AM -0700, Christian Tanzer wrote:

> Ralf: please fix encoding issue in converter (J�rgen Schweizer) and
> pass on to the Grazers.

Can you please check your version of rsclib, mine seems to work:

> > > scope.PAP.Person.query (last_name = 'schweizer').first()
> > > PAP.Person ('schweizer', 'j\xfcrgen', '', '')
> > > 
> > > from rsclib import Version
> > > print Version.VERSION
> > > 0.45

The latest change relevant to the SQL parser was Juni 2014 (!).

To check directly from the sql dump (maybe you have a different dump?)
I checked with latest from today:

#!/usr/bin/python
import sys
from   rsclib.sqlparser       import make_naive, SQL_Parser

p = SQL_Parser (verbose = False, fix_double_encode = 1)
p.parse (sys.stdin)

for p in p.contents ['person'] :
    if p.lastname == 'Schweizer' :
        print repr (p.firstname)

(and, yes, the converter also uses fix_double_encode option)

## Ralf

Dr. Ralf Schlatterbeck                  Tel:   +43/2243/26465-16
Open Source Consulting                  www:   http://www.runtux.com
Reichergasse 131, A-3411 Weidling       email: office@runtux.com
allmenda.com member                     email: rsc@allmenda.com

**Comment by tanzer** [comment] 2015-06-22 10:13
Upgrading rsclib does fix the encoding issue. 
eddie and my development machine both used rsclib v 0.41: I upgraded both just now.

The problem is one of communication: you need to tell us, when an upgrade is necessary!

**Comment by tanzer** [comment] 2015-06-22 10:16
@equinox0815: I changed the fixtures in commit https://github.com/FunkFeuer/Graz/commit/ce2fcf2fb65c4d277b7bb61ecfb00b5344bba378. You can change the predefined superuser accounts by editing the file fixtures.py of this repository.

**Closed as completed by tanzer** 2015-06-22 10:16 UTC
Labels: bug
